const divRoot = {
  align: "",
  title: "",
  lang: "",
  translate: true,
  dir: "",
  hidden: false,
  accessKey: "",
  draggable: false,
  spellcheck: true,
  autocapitalize: "",
  contentEditable: "inherit",
  isContentEditable: false,
  inputMode: "",
  offsetParent: body,
  offsetTop: 0,
  offsetLeft: 0,
  offsetWidth: 1528,
  offsetHeight: 2827,
  style: CSSStyleDeclaration {alignContent: "", alignItems: "", alignSelf: "", alignmentBaseline: "", all: "", …},
  dataset: DOMStringMap {},
  nonce: "",
  autofocus: false,
  tabIndex: -1,
  enterKeyHint: "",
  namespaceURI: "http://www.w3.org/1999/xhtml",
  localName: "div",
  tagName: "DIV",
  id: "root",
  className: "",
  classList: DOMTokenList [value: ""],
  slot: "",
  attributes: NamedNodeMap {0: id, id: id, length: 1},
  part: DOMTokenList [value: ""],
  innerHTML: "<nav class="uk-navbar"><div class="uk-navbar-right",
  outerHTML: "<div id="root"><nav class="uk-navbar"><div class="",
  scrollTop: 0,
  scrollLeft: 0,
  scrollWidth: 1528,
  scrollHeight: 2827,
  clientTop: 0,
  clientLeft: 0,
  clientWidth: 1528,
  clientHeight: 2827,
  attributeStyleMap: StylePropertyMap {size: 0},
  elementTiming: "",
  children: HTMLCollection(4) [nav.uk-navbar, div.uk-container.uk-margin-top, div.logo-strip-container, footer.footer-container],
  firstElementChild: nav.uk-navbar,
  lastElementChild: footer.footer-container,
  childElementCount: 4,
  nodeType: 1,
  nodeName: "DIV",
  baseURI: "http://localhost:3000/",
  isConnected: true,
  ownerDocument: document,
  parentNode: div#app,
  parentElement: div#app,
  childNodes: NodeList(4) [nav.uk-navbar, div.uk-container.uk-margin-top, div.logo-strip-container, footer.footer-container],
  firstChild: nav.uk-navbar,
  lastChild: footer.footer-container
}
